# Generated by Django 3.2.5 on 2021-08-10 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone Number Is Not Correct!', regex='^((\\+98|0)9\\d{9})$')], verbose_name='Phone Number'),
        ),
    ]
