# Generated by Django 3.2.5 on 2021-08-10 11:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('national_code', models.IntegerField(help_text='National Code of Customer', null=True, validators=[django.core.validators.RegexValidator(message='National Code Is Not Correct!', regex='^[0-9]{10}$')], verbose_name='National Code')),
                ('birth_day', models.DateField(help_text='Birth Day of Customer', null=True, verbose_name='Birth Day')),
                ('user', models.ForeignKey(help_text='Customer Id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
