# Generated by Django 3.2.5 on 2021-08-10 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('purchase_date', models.DateTimeField(help_text='Date of Purchase', verbose_name='Date')),
                ('status_order', models.CharField(choices=[('processing', 'PROCESS'), ('canceled', 'CANCEL'), ('paid', 'PAID'), ('SEND', 'SEND')], default='processing', help_text='Status of Order, example: processing, paid, ...', max_length=10, verbose_name='Order Status')),
                ('customer_id', models.ForeignKey(help_text='Customer of Order', on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='Customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(help_text='Quantity of  SubOrder', verbose_name='Quantity')),
                ('order_id', models.ForeignKey(help_text='Order of  SubOrder', on_delete=django.db.models.deletion.CASCADE, to='order.ordered', verbose_name='Order')),
                ('product_id', models.ForeignKey(help_text='Product of Order', on_delete=django.db.models.deletion.CASCADE, to='product.products', verbose_name='Product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
