# Generated by Django 3.2.5 on 2021-08-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordered',
            name='status_order',
            field=models.CharField(choices=[('processing', 'PROCESS'), ('paid', 'PAID')], default='processing', help_text='Status of Order, example: processing, paid, ...', max_length=10, verbose_name='Order Status'),
        ),
    ]
