# Generated by Django 3.2.5 on 2021-08-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_ordered_status_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordered',
            name='status_order',
        ),
        migrations.AddField(
            model_name='ordered',
            name='complete',
            field=models.BooleanField(default=False, help_text='Status of Order, example: True, False, ...', verbose_name='Order Status'),
        ),
    ]
