# Generated by Django 3.2.5 on 2021-08-18 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210816_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproduct',
            name='order_id',
            field=models.ForeignKey(help_text='Order of  SubOrder', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order.ordered', verbose_name='Order'),
        ),
    ]
